# Copyright Buzea Alexandru-Mihai-Iulian 321CAb

run-p1:
	octave solve_householder.m
run-p2:
	octave solve_gpp.m
run-p3:
	octave solve_gpps.m
run-p4:
	octave solve_conjugate_gradient.m
run-best:
	octave solve_householder.m

pack:
	zip -r alexandru.buzea2007.zip ./*